# Textos de la aplicacion
menu.texto.titulo=GESTOR DE ACTORES Y PELÍCULAS
menu.texto.utilidades=Utilidades
menu.texto.seleccionar.opcion=Seleccione una opción:
menu.opcion.1.insertar.ruta=Introduzca la ruta de la carpeta (presione ENTER para {0}): 
menu.opcion.2.input.actor=Introduzca el ID o nombre del actor/actriz: 
menu.opcion.2.actor.no.encontrado=No se ha encontrado el actor/actriz.
menu.opcion.2.actor.encontrado=Actor/actriz encontrado/a: 
menu.opcion.10.utilidades.volver=Volviendo al menú principal...
menu.opcion.0.saliendo=Saliendo...
# Opciones de los menus.
menu.opcion.0.salir=0. Salir
menu.opcion.0.atras=0. Atras.
menu.opcion.1.cargar.datos=1. Cargar los datos desde los ficheros.
menu.opcion.1.recargar.datos=1. Volver a cargar los datos desde los ficheros.
menu.opcion.2.buscar.actor=2. Buscar un actor/actriz. (Por ID)
menu.opcion.3.insertar.actor=3. \u001B[9mInsertar un nuevo actor/actriz.\u001B[0m
menu.opcion.4.peliculas.actor=4. \u001B[9mDevolver (no imprimir) las películas de un actor.\u001B[0m
menu.opcion.5.actores.peliculas=5. \u001B[9mDevolver (no imprimir) los actores de una película.\u001B[0m
menu.opcion.6.modificar.anio=6. \u001B[9mModificar el año de estreno de una película.\u001B[0m
menu.opcion.7.borrar.actor=7. \u001B[9mBorrar un actor/actriz.\u001B[0m
menu.opcion.8.guardar.fichero=8. \u001B[9mGuardar la lista en un fichero.\u001B[0m
menu.opcion.9.actores.nomApe=9. \u001B[9mObtener una lista de actores ordenada por nombre y apellido.\u001B[0m
menu.opcion.10.utilidades=10. Utilidades
menu.opcion.10.1.letras.raras=10.1. Buscar letras raras.




#Mensajes de informacion
msg.info.procesar.fichero=Procesando contenido de: {0}
# Mensajes de validaciones
msg.opcion.validar.id.numerico= El ID ha de ser numerico.
msg.opcion.invalida=Opción no válida.
#Mensajes de error
msg.error.acceso.carpeta=Error accediendo a carpeta: {0}
