menu.texto.titulo====== GESTOR DE ACTORES Y PELÍCULAS =====
menu.texto.extra.utilidades=Utilidades
menu.opcion.objetivo.1=1. Cargar los datos desde los ficheros.
menu.opcion.objetivo.1.bis=1. Volver a cargar los datos desde los ficheros.
menu.opcion.objetivo.1.input.ruta=Introduzca la ruta de la carpeta (presione ENTER para {0}): 
menu.opcion.objetivo.2=2. Buscar un actor/actriz. (Por ID)
menu.opcion.objetivo.2.id.no.valido= El ID ha de ser numerico.
menu.opcion.objetivo.2.input.actor=Introduzca el ID o nombre del actor/actriz: 
menu.opcion.objetivo.2.actor.no.encontrado=No se ha encontrado el actor/actriz.
menu.opcion.objetivo.2.actor.encontrado=Actor/actriz encontrado/a: 
menu.opcion.objetivo.3=3. \u001B[9mInsertar un nuevo actor/actriz.\u001B[0m
menu.opcion.objetivo.4=4. \u001B[9mDevolver (no imprimir) las películas de un actor.\u001B[0m
menu.opcion.objetivo.5=5. \u001B[9mDevolver (no imprimir) los actores de una película.\u001B[0m
menu.opcion.objetivo.6=6. \u001B[9mModificar el año de estreno de una película.\u001B[0m
menu.opcion.objetivo.7=7. \u001B[9mBorrar un actor/actriz.\u001B[0m
menu.opcion.objetivo.8=8. \u001B[9mGuardar la lista en un fichero.\u001B[0m
menu.opcion.objetivo.9=9. \u001B[9mObtener una lista de actores ordenada por nombre y apellido.\u001B[0m
menu.opcion.extra.salir=0. Salir
menu.opcion.extra.utilidades=10. Utilidades
menu.opcion.extra.utilidades.1=1. Buscar letras raras.
menu.opcion.atras=0. Atras.
menu.opcion.extra.utilidades.volver=Volviendo al menú principal...
menu.opcion.extra.saliendo=Saliendo...
menu.texto.seleccionarOpcion=Seleccione una opción:
msg.opcion.invalida=Opción no válida.


